/*
 * bill_acceptor_manager.h
 *
 *  Created on: Jun 2, 2023
 *      Author: xuanthodo
 */

#ifndef INC_DEVICEMANAGER_BILLACCEPTORMANAGER_H_
#define INC_DEVICEMANAGER_BILLACCEPTORMANAGER_H_

#include "stdio.h"
#include "stdbool.h"
#include "Device/billacceptor.h"

/**
 * Status
 */
enum {
	STATUS_SUCCESS = 0x00,
	STATUS_DEFECTIVE_MOTOR = 0x01,
	STATUS_SENSOR_PROBLEM = 0x02,
	STATUS_VALIDATOR_BUSY = 0x03,
	STATUS_ROM_CHECKSUM_ERROR = 0x04,
	STATUS_VALIDATOR_JAMMED = 0x05,
	STATUS_VALIDATOR_WAS_RESET = 0x06,
	STATUS_BILL_REMOVED = 0x07,
	STATUS_CASHBOX_OUTOF_POSITION = 0x08,
	STATUS_VALIDATOR_DISABLE = 0x09,
	STATUS_INVALID_ESCROW_REQ = 0x0A,
	STATUS_BILL_REJECTED = 0x0B,
	STATUS_POSSIBLE_CREDITED_BILL_REMOVAL = 0x0C,
	STATUS_NB_ATTEMP_INPUT_BILL = 0x0D
};

bool BILLACCEPTORMNG_init();
bool BILLACCEPTORMNG_run();
uint8_t BILLACCEPTORMNG_get_state();
uint8_t BILLACCEPTORMNG_get_status();
bool BILLACCEPTORMNG_is_error();
bool BILLACCEPTORMNG_is_accepted();
bool BILLACCEPTORMNG_clear_accepted();
uint32_t BILLACCEPTOR_get_last_bill_accepted();
void BILLACCEPTORMNG_enable();
void BILLACCEPTORMNG_disable();
bool BILLACCEPTORMNG_is_enabled();


#endif /* INC_DEVICEMANAGER_BILLACCEPTORMANAGER_H_ */
